# Replace the group below with an actual group (like me.myproductions.willowtrees)
group=com.example.spoutexampleplugin
# Increment the version below when needed, and add -SNAPSHOT for development versions
version=0.1-SNAPSHOT
# Choose the Bukkit API version below
apiVersion=26.1.2
# Choose the Spout version below (see https://github.com/ModernSpout/Spout/releases)
spoutVersion=1.13
# Replace the description below with your own description
description=Adds nice blocks and items
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
