# Put your own plugin name below
name: YourPluginNameHere
description: $description
version: '$version'

# Replace with your own classes
main: com.example.spoutexampleplugin.ExamplePlugin
bootstrapper: com.example.spoutexampleplugin.ExamplePluginBootstrap
# Choose the right API version here
api-version: '26.1.2'
load: POSTWORLD

# Add yourself below
authors: []
# Replace with your own website
website: https://github.com/ModernSpout/Spout-plugin-template
